{% set name = "semi-ate-project-database" %}
{% set version = "1.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semi-ate-project-database-{{ version }}.tar.gz
  sha256: 4a8861fac98cbbd6b857317e282a8fb3a43e97dda0d34dac469b13f3f7efbe39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ate_projectdatabase
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-project-database/
  summary: Project database of ATE test projects
  license: GPL-2.0-only
  license_file: ate_projectdatabase/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
