{% set name = "semi-ate-project-database" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-project-database-{{ version }}.tar.gz
  sha256: 8f6c91d54e0ee9ef87018a28068611a99666244b11d393b8fcbc5c55917411af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - ate_projectdatabase
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-project-database/
  summary: Project database of ATE test projects
  license: GPL-2.0-only
  license_file: ate_projectdatabase/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
